### ISSUE TITLE
Gateway: 3rd Test release report.

### ISSUE THREAD

**Issue by sk-enya** [bobanetwork/boba_legacy#1140]
- [x] If a user switches to a network in MM - then the gateway should switch the UI for them but correctly it's forcing user to connect back previous active network  
- [x] Wallet Connect V2: addressing separately at [AddWallet V2](https://github.com/bobanetwork/gateway/issues/77)
- [x] UI reported issues from Yonhee as per the attached pdf. [gateway_boba_feedback.pdf](https://github.com/bobanetwork/boba/files/12396693/gateway_boba_feedback.pdf) [issue links](https://github.com/bobanetwork/gateway/issues/32)
- [x] Adding ETH to the wallet here adds the incorrect contract address (the others are fine). Please double check all contract addresses on all networks. : [address separately issue](https://github.com/bobanetwork/gateway/issues/61)

**Comment by InoMurko** [comment]
<img width="731" alt="image" src="https://github.com/bobanetwork/boba/assets/2582555/1c3694eb-4f75-4ca3-bbac-6e0990d4d749">

`UNDEFINED`
HOOVER on questionmark top right

**Comment by sk-enya** [comment]
Closing as we have created subtask for each item.
