### ISSUE TITLE
Remove BobaBeam (Moonbeam) and BobaOpera (Fantom) from repo - Checklist

### ISSUE THREAD

**Issue by souradeep-das** [bobanetwork/boba_legacy#820]
## Overview
Things that will have to be done after the BobaBeam and BobaOpera networks are shut down

## Checklist

- [ ] turn off BobaLink, gasPriceOracle services for the networks
- [ ] remove Teleportation support, pause contracts on Moonbeam/Fantom (LayerZero bridges connecting Ethereum and Moonbeam/Fantom will remain, as they are unrelated to Boba)
- [ ] update Token Lists
- [ ] remove dockerfiles and docker-compose files
- [ ] remove from boba-sdk and boba-relayer sdk service
- [ ] remove from docs
- [x] remove from gateway

**Comment by vortex-hue** [comment]
hi @souradeep-das  , please can I get assigned to this task, and I'd get to work on it as soon as possible.
